name: stratis_gui_flutter
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.8.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  stratis_flutter:
    path: ../plugins/stratis_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true